[package]
name = "gen_all_strings"
version = "0.1.0"
authors = ["Mohammad Al Zouabi <62098043+aboqasem@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
